[package]
edition = "2021"
name = "identitycreator"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrsc = {path = "../rust-vrsc/"}
vrsc-rpc = {path = "../rust-vrsc-rpc/client"}
